# Install python and aptitude on the target machines (apt-get install python aptitude)
# Copy ssh public key to machines (ssh-copy-id user@host)
---
- name: Install Rails Server
  hosts: webservers
  # After initial provisioning, use deploy instead of root
  remote_user: root
  # remote_user: deploy
  # become: yes
  # become_method: sudo
  gather_facts: no # don't gather facts because /usr/bin/python isn't set
  pre_tasks:
    - name: apt-get update
      raw: apt-get update -qq
    - name: install python 2.7 and aptitude
      raw: apt-get install -qq python2.7 aptitude
    - name: set python 2.7 as default
      raw: update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
    - name: apt-get udate
      raw: sudo apt-get update
    - name: install rvm
      raw: sudo apt-get install rvm
      raw: rvm install 2.5.3
      raw: sudo mkdir /var/www/rubie
      raw: sudo chown username:username /var/www/rubie
    - name: apt-get common
      raw: sudo apt-get install software-properties-common
      raw: git clone https://github.com/rvm/ubuntu_rvm
      raw: sudo apt-add-repository -y ppa:rael-gc/rvm
    - name: apt-get rvm
      raw: sudo apt-add-repository -y ppa:rvm/rvm
      raw: sudo apt-get update
      raw: sudo apt-get install rvm
    - name: apt-get xvfb
      raw: sudo apt-get install xorg 
      raw: sudo apt-get install xvfb
      raw: sudo apt-get install xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic
    - name: apt-get bundler
      raw: gem install bundler -v 1.17.3
      raw: sudo apt-get install libcurl4-openssl-dev
    - name: sudo apt-get install curl
      raw: apt-get install curl
    
    roles:
    - common
    - deploy-user
    - mysql
    - nginx
    - certbot
    - ruby
    - rails
    - monit
    - memcached
    - redis
    - elasticsearch
